"""
Cost Trends page
----------------
Shows the cost forecast as a line chart with controls.

Why a separate page?
- Forecasting is a specific question ("what will I spend?") that
  deserves its own canvas with its own controls.
- Keeping the home page clean is more important than dumping
  every chart on it.
"""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

import pandas as pd
import streamlit as st

from src.dashboard.api_client import fetch_forecast

st.set_page_config(page_title="Cost Trends", page_icon="📊", layout="wide")
st.title("📊 Cost Trends & Forecast")
st.caption("Predicted daily cloud spend, generated by the linear regression model.")

# -------- Controls --------
days_ahead = st.slider(
    "Forecast horizon (days)",
    min_value=7, max_value=90, value=30, step=7,
    help="How far into the future to predict. Linear regression "
         "is reliable for ~3 months; beyond that, error grows.",
)

# -------- Fetch + chart --------
forecast = fetch_forecast(days_ahead=days_ahead)
df = pd.DataFrame(forecast["forecast"])
df["date"] = pd.to_datetime(df["date"])

# -------- KPIs above the chart --------
c1, c2, c3 = st.columns(3)
c1.metric("Days ahead", forecast["days_ahead"])
c2.metric("Total predicted cost", f"₹{forecast['total_predicted_cost_inr']:,.0f}")
c3.metric("Average daily cost", f"₹{forecast['average_daily_cost_inr']:,.0f}")

# -------- The chart --------
st.subheader("Predicted Daily Cost")
st.line_chart(df.set_index("date")["predicted_cost_inr"], height=400)

# -------- The data table (collapsible) --------
with st.expander("📋 View raw forecast data"):
    df_display = df.copy()
    df_display["date"] = df_display["date"].dt.strftime("%Y-%m-%d")
    df_display["predicted_cost_inr"] = df_display["predicted_cost_inr"].apply(
        lambda x: f"₹{x:,.2f}"
    )
    st.dataframe(df_display, use_container_width=True, hide_index=True)

# -------- A caveat (always be honest about model limitations) --------
st.info(
    "ℹ️ **Model note:** This forecast uses linear regression on time features "
    "(day of week, month, trend). It will underestimate sudden spikes from new "
    "workloads or anomalies. Use it as a baseline, not a guarantee."
)